In [ ]:
#OPERATIONS ON NumPy

In [3]:
#create 1D array
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [11]:
#create 2D array with 6 rows and 5 columns
import numpy as np
arr=np.zeros((6,5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#create 2D array with zeros and ones
import numpy as np
arr=np.eye(2)
print(arr)


[[1. 0.]
 [0. 1.]]


In [15]:
#create a full function with 2D array, filler of 7
import numpy as np
arr=np.full((2,2),7)
print(arr)

[[7 7]
 [7 7]]


In [19]:
#implement slicing
import numpy as np
arr=np.full((2,2),7)
print (arr)
arr[:,:]

[[7 7]
 [7 7]]


array([[7, 7],
       [7, 7]])

In [40]:
import numpy as np
arr=np.eye(5)
print(arr)
print(arr[2:5,0:3])
print(arr[0:2,0:5])
print(arr[2:4:,2:4])
print(arr[-3:-1,-3:-1])
print(arr[-4:-1,-4:-1])


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
