In [3]:
# indexing of an array 
import numpy as np
a=np.array1=([[[1,2,3,4],[5,6,7,8],[4,7,8,3]],
               [[1,2,3,4],[1,4,6,8],[8,6,7,3]],
               [[7,4,5,6],[3,4,1,2],[6,7,3,4]]])

b=([[[1,2,3,4],[5,6,7,8],[4,7,8,3]],
               [[1,2,3,4],[1,4,6,8],[8,6,7,3]],
               [[7,4,5,6],[3,4,1,2],[6,7,3,4]]])
print(a+b)

[[[1, 2, 3, 4], [5, 6, 7, 8], [4, 7, 8, 3]], [[1, 2, 3, 4], [1, 4, 6, 8], [8, 6, 7, 3]], [[7, 4, 5, 6], [3, 4, 1, 2], [6, 7, 3, 4]], [[1, 2, 3, 4], [5, 6, 7, 8], [4, 7, 8, 3]], [[1, 2, 3, 4], [1, 4, 6, 8], [8, 6, 7, 3]], [[7, 4, 5, 6], [3, 4, 1, 2], [6, 7, 3, 4]]]


In [12]:
import numpy as np 
arr1 = np.array([[1,2,3,4], [5,6,7,8], [3,4,6,2]])
print(arr1)
print(arr1.flags)
print(arr1.shape)
print(arr1.strides)
print(arr1.ndim)
print(arr1.data)                                                      
print(arr1.itemsize)
print(arr1.base)
print(arr1.nbytes)
print(arr1.T)
print(arr1.real)
print(arr1.imag)
print(arr1.size)


[[1 2 3 4]
 [5 6 7 8]
 [3 4 6 2]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(3, 4)
(16, 4)
2
4
None
48
[[1 5 3]
 [2 6 4]
 [3 7 6]
 [4 8 2]]
[[1 2 3 4]
 [5 6 7 8]
 [3 4 6 2]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
12
